### ISSUE TITLE
User Story: Dispatch Red Rose font

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery-dashboard#105]
I would like Viviana to use your dispatcher to push https://github.com/magictype/redrose to google/fonts. The font has been mastered and can be pushed.

This is a good opportunity for us to find out which steps are unintuitive.

**Comment by graphicore** [comment]
I'm closing this. Red Rose is still open google/fonts#1672

But the tool is used and we're collecting feedback:

@vv-monsalve did:
 * google/fonts#2207
 * google/fonts#2208

and @m4rc1e did:

 * google/fonts#2203
 * google/fonts#2204
 * google/fonts#2205
