### ISSUE TITLE
[Font Bakery Dashboard] fail to create family: Bebas Neue

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery-dashboard#124]
GitHub PR Server can't dispatch Pull Request. ERROR Error: Signature author is required. / Don't understand what it means.
Also,"designated GitHub branch page" (link) was broken

full report

Step # 2 Create the Pull Request
finished: FAILED

Failing with reason:

Task SignOffAndDispatch FAILED
GitHub PR Server can't dispatch Pull Request.

ERROR Error: Signature author is required.

designated GitHub branch page

[full report](https://fontbakery.graphicore.de/dispatcher/process/b0772482-0fde-4afd-bd15-88bc719db260)

# Step # 2 Create the Pull Request

**finished: FAILED**

Failing with reason: 

### Task SignOffAndDispatch FAILED

**GitHub PR Server** can't dispatch Pull Request.

 **ERROR** Error: Signature author is required.

[designated GitHub branch page](https://github.com/graphicore/googleFonts/tree/Font_Bakery_Dispatcher_2019_09_12_ofl_bebasneue)

**Comment by graphicore** [comment]
Alright, about the "Signature author is required" message. I'm using the public email address of the login that is requesting the PR to create the commit. If the GitHub profile doesn't specify a public email, the commit will not be linked to the login. There are for sure other possibilities, but right now, I just changed the error message to a more verbose one, here for the example of @graphicoredummy:

> **GitHub PR Server** can't dispatch Pull Request.
> **ERROR** Error: Can't create a commit signature for name: @graphicoredummy, because there's no public email address set in the GitHub profile. If you are @graphicoredummy, please go to https://github.com/settings/profile and update the "Public email" entry.

Generally, if you are using git from the command line and if it is set up properly, the email to use is probably the same as the result of calling `git config --get user.email` in the terminal.

**Comment by graphicore** [comment]
No, it's not like that. The Dispatcher will create a commit in your name and also create the PR or Issues in your name. So that's all things you would do yourself in any way.

**Comment by vv-monsalve** [comment]
Yes, I meant the commit and any task associated with the uploading process. 
My original doubt was if that email for the process would remain once it was published, but is clear now that it will not.
Thanks for addressing this.
