### ISSUE TITLE
[Font Bakery Dashboard] fail to update family: ABeeZee

### ISSUE THREAD

**Issue by graphicoredummy** [googlefonts/fontbakery-dashboard#128]
Can this user file an issue in the FBD repository? 

[full report](https://fontbakery.graphicore.de/dispatcher/process/db2755a2-dc8f-40ad-9c5d-1cd9004c7d5a)

# Step # 0 Review the Request and Generate the Files Package

**finished: FAILED**

Failing with reason: testing

### Task ApproveProcess FAILED

looking into [#113](https://github.com/googlefonts/fontbakery-dashboard/issues/113)

Report…

### Files
 * `ABeeZee-Italic.ttf` *47764 Bytes*
 * `ABeeZee-Regular.ttf` *46124 Bytes*
 * `DESCRIPTION.en_us.html` *345 Bytes*
 * `FONTLOG.txt` *1765 Bytes*
 * `METADATA.pb` *626 Bytes*
 * `OFL.txt` *4466 Bytes*

[zip file download](/download/persistence/a51770aeaf3d57a835da37f38b1dde3313ad4b6d747e49255385785782f2810e:c/ABeeZee.zip)

### Metadata
**commit** 1de10e9a33fbe586897d35f9da29ab95df1b6d37  
**commitDate** 2015-06-15T19:55:05.000Z  
**sourceDetails** 

&emsp;**status** `"OK"`  
&emsp;**name** `"ABeeZee"`  
&emsp;**keySuffix** `""`  
&emsp;**nameConfirmed** `"Passed"`  
&emsp;**upstream** `"https://github.com/googlefonts/abeezee.git"`  
&emsp;**branch** `""`  
&emsp;**fontfilesPrefix** `"fonts/ttf/ABeeZee-"`  
&emsp;**genre** `"Sans Serif"`  
&emsp;**designer** `""`  
**familyPath** fonts/ttf  
**repository** https://github.com/googlefonts/abeezee.git  
**branch** master  
**googleMasterDir** ofl/abeezee  
**isUpdate** `true`  
**licenseDir** ofl

**Comment by graphicore** [comment]
Used this trying to reproduce #113, but I couldn't.
