### ISSUE TITLE
Bug: Font Designer not in METADATA.pb

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery-dashboard#141]
Doing the process for Alata, FontBakery reported the following:

> **FAIL com.google.fonts/check/metadata/unknown_designer** Font designer field in METADATA.pb must not be 'unknown'.
> FAIL Font designer field is 'UNKNOWN'

Nevertheless, inspecting the spreadsheet to confirm it, there was the Designer name written, so it should fill the METADATA.pb field.

[Link to the process](https://fontbakery.graphicore.de/report/849b7584-eecc-45b8-a73e-e85693403968)

**Comment by graphicore** [comment]
> [Link to the process](https://fontbakery.graphicore.de/report/849b7584-eecc-45b8-a73e-e85693403968)

That's the Font Bakery report not the process.

**Comment by vv-monsalve** [comment]
It worked today, I think this could be related to the last night cluster issue

**Comment by graphicore** [comment]
The "cluster fuck" I say :laughing:
