### ISSUE TITLE
[dispatcher] Initializing process: family information is missing

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery-dashboard#169]
![Screen Shot 2020-04-08 at 12 06 40](https://user-images.githubusercontent.com/48698976/78827124-41956d80-79a8-11ea-8c78-1b06274bc390.png)

The error message could be more explanatory to guide the user. On chat with @graphicore it was settled to:

```
The request cannot be processed because the family information is missing.
This can happen when either the family is not listed or the server has not yet received the latest information. Please wait a moment and try again. If the problem persists please file an issue.
```

**Comment by graphicore** [comment]
To add more context:

It looks like this is a caching problem that is not located in the dashboard. Either it's some network layer caching or on the google spreadsheet API that is used to store/read this data.
The dashboard code explicitly uses no caching in these requests, to be as up to date as possible.
It's interesting that the drop down (via `uiPreInit`) received the family entry, but the `checkUpdate` function of `FamilyPRDispatcherProcess` did not, despite of running considerably after `uiPreInit`.
