### ISSUE TITLE
Develop a list of upstream URLs for every family in google/fonts

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery-dashboard#33]
The key feature of the 0.1.0 release of the dashboard for me is to be able to say, this is the FB score of the fonts in X family in production, and this is the FB score of the fonts in the upstream. 

To do that, we need to develop a complete list of upstream URLs for every family in google/fonts. 

See https://github.com/googlefonts/fontbakery/issues/291 and https://github.com/googlefonts/fontbakery/pull/1262

**Comment by m4rc1e** [comment]
@davelab6 We currently have a Google doc for this. I've resent you a link to it.

**Comment by davelab6** [comment]
Thanks!

**Comment by davelab6** [comment]
http://chriszarate.github.io/sheetrock/ may be helpful for this

**Comment by davelab6** [comment]
Closing as duplicate of #15
