### ISSUE TITLE
The reported dates are wrong and changing...

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery-dashboard#4]
All from:  http://104.197.213.179/report/9cabce25-26db-4d14-85c5-41b4ff3e42f3
![selection_147](https://user-images.githubusercontent.com/393132/27225667-859f660c-529b-11e7-90d7-65f444488a7c.png)

![selection_148](https://user-images.githubusercontent.com/393132/27225672-898f5baa-529b-11e7-8979-5d40ec287407.png)

![selection_149](https://user-images.githubusercontent.com/393132/27225675-8d684f66-529b-11e7-887a-8390f9418f6e.png)

Started/Finished should never change after it was written once.

**Comment by davelab6** [comment]
Is this fixed by your work on #41?

**Comment by graphicore** [comment]
Let it open for the moment. I guess RabbitMQ did redeliver the jobs, because they were long running and the `ack` did not come in time for the timeout. If that was the case, it is not fixed yet.

**Comment by graphicore** [comment]
Or it was something else:

> There aren't any message timeouts; RabbitMQ will redeliver the message when the consumer dies. It's fine even if processing a message takes a very, very long time.

(https://www.rabbitmq.com/tutorials/tutorial-two-python.html)

We don't know yet.
