### ISSUE TITLE
Update drag and drop to use fontbakery >= version 0.3.0

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery-dashboard#41]
Font Bakery now has a new output format, thus, we need to redo the report saving and rendering part. This will improve real time reporting and we also have the opportunity to do parallel execution of tests, which would be nice to have:

## Things that need to be done (most "at the same time")

- [x] update worker to invoke the new Font Bakery
- [x] change test report format in the database
- [x] create a new test reporter for the new report format
- [x] update database report-record on a per test base (or per message?) (== real time pushes to browser)
- [ ] adopt test report rendering (in the browser/javascript) to new style tests
- [ ] We should have just one Font Bakery worker for drag and drop, dashboard etc. so make it reusable
- [x] enable (worker) distributed/parallel test execution (per process distributed on a multi-core cpu would be awesome as well!)
- [x] for parallel execution one worker would act as the master and dispatch subset-jobs via AMQP.

Parallel execution can be done after all the other things, when done carefully it'll just work :smile: 

## Other Important

- [ ] all the crazy dependencies need to be in the workers: msfontvalidator, pyfontaine, fontforge, Apple ftxvalidator (use an external OSX-server cloud provider?, ask Apple to make a linux compatible binary :joy_cat: )
- [ ] clean up repository if already possible, better docs
- [ ] begin to plan dashboard (issues has a lot of feature requests)
- [ ] It would be awesome to have self-updating workers :imp: why do a docker push etc.pp if the worker could just run pip install itself (... ok, this is playing the implications down). It would also make it more straight forward to re-run tests. As when the repository changes, we need to re-run when the workers are updated, it's basically both input for us.
- [ ] configuring development/minikube and deployment/gcloud is tortuous

**Comment by felipesanches** [comment]
The goal should be fontbakery >= 0.3.1 (the 0.3.0 release was broken; the issues were then addressed on a quick follow-up 0.3.1 release)

**Comment by graphicore** [comment]
The APIs didn't change.

**Comment by felipesanches** [comment]
I want to showcase the dashboard at ATypI. Can I help with some coding here?

@graphicore Can you please update the check-boxes in the description of this issue in case some of them are already implemented? How do you see a way for me to help here?

**Comment by graphicore** [comment]
Allright, I checked some items and created branches on googlefonts:

* https://github.com/googlefonts/fontbakery/tree/dashboard_related
* https://github.com/googlefonts/fontbakery-dashboard/tree/draganddrop

**Comment by davelab6** [comment]
>  adopt test report rendering (in the browser/javascript) to new style tests

Could you use https://material.io/components/web/ please?

**Comment by graphicore** [comment]
> Could you use https://material.io/components/web/ please?

Yet another material framework?

**Comment by felipesanches** [comment]
It seems to be the same one we discussed in the past, if I recall correctly.

**Comment by graphicore** [comment]
There must be even more, but last year Material Design Lite: https://getmdl.io/ was the thing.

**Comment by felipesanches** [comment]
I think that any one of these would be great. Unless @davelab6 has some reason to pick a specific one like https://material.io/components/web/ the choice seems to be pretty much up to you.

Even though Font Bakery is not an official/supported Google product, I think the reason why Dave asked for it is to get an elegant look and feel that is familiar to users of Google products (as well as effective in terms of the user experience, off course).

**Comment by graphicore** [comment]
The one thing I don't like about these frameworks is that they seem to have a TTL of less than year. I appreciate not having to write so much style related CSS and HTML though. Oh, yeah, another thing is that the HTML is usually very idiosyncratic. Another attendee could be [polymer paper elements](https://www.webcomponents.org/collection/PolymerElements/paper-elements), which I also never used and can't say how good it is, but the web components concept could help (or make it worse).

**Comment by graphicore** [comment]
Here's another one: https://material.angular.io/, the older AngularJS has it's own implementation of course: https://material.angularjs.org

**Comment by davelab6** [comment]
MDC is the latest and greatest, superceding mdl and paper
