### ISSUE TITLE
Enable fontforge checks

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery-dashboard#5]
Originaly submitted at https://github.com/googlefonts/fontbakery/issues/1298

Fontforge checks are not currently running on the worker container.

Fontforge instalation commands were added to the worker container image (via Dockerfile apt-get install statements) but the fontforge python module is not found at runtime.

**Comment by davelab6** [comment]
@felipesanches can this be closed?

**Comment by felipesanches** [comment]
This is about having fontforge properly installed and functional on the worker container. @graphicore is in a better position to let us know if the current setup of fontforge on the worker container fullfils that requirement or if it is still misconfigured.

**Comment by graphicore** [comment]
fontforge is working at the moment: https://github.com/googlefonts/fontbakery-dashboard/blob/8a11f1783606c1eb600f43a326416652321fc762/containers/worker-fontbakery/Dockerfile#L5-L8
