### ISSUE TITLE
Implement main overview table

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery-dashboard#51]
![1_181](https://user-images.githubusercontent.com/393132/30764601-bc089b80-9fb9-11e7-9e34-382fb5ff0302.png)

* switch total/percentages (default percentages)
* switch static latest finished, daily/live progress

FAMILY | Upstream Pulls | Upstream Master | gh google/fonts pulls | gh google/fonts master | DEV API | Public API
--- | --- | --- | --- | --- | --- | ---
Poppins | 7% | 6% | 5% | 8% | 9% | 17%
Roboto | … | … | … | … | … | …
TOTAL | 12%  | 13% | 14% | 15% | 16% | 17%

Historical Data: the state of this table a year ago, three years ago, ...

The live updating view: will be implemented after the static one.

Sources, here the rows, will be implemented from right to left. API first ...

The *Upstream* sources will likely be augmented with METADATA.pb etc. from google/fonts:master

There will be a drill down. A column here can be expanded to a full collection report table. The imploded column shows the value of FAIL.

example collection report table:

family_dir | total | ERROR | FAIL | WARN | SKIP | INFO | PASS
-- | -- | -- | -- | -- | -- | -- | --
ofl/laosanspro | 124 | 4 | 8 | 5 | 47 | 3 | 57
ofl/miriamlibre | 222 | 10 | 8 | 12 | 4 | 6 | 182
ofl/orbitron | 418 | 16 | 43 | 21 | 24 | 12 | 302
ofl/pontanosans | 124 | 4 | 19 | 8 | 4 | 3 | 86
ofl/poppins | 1790 | 72 | 151 | 83 | 54 | 56 | 1374

**Comment by davelab6** [comment]
Using the historical data, I want burn down charts

Felipe said something about heatmap coloring which is a good idea
