### ISSUE TITLE
Use HTTPS for dashboard

### ISSUE THREAD

**Issue by DunwichType** [googlefonts/fontbakery-dashboard#85]
HTTPS for https://fontbakery.com/dashboard is broken, so it won’t load in browsers.
<img width="839" alt="screen shot 2018-10-04 at 7 20 56 pm" src="https://user-images.githubusercontent.com/3534596/46511238-a64b9700-c80a-11e8-8e07-16809da31fcd.png">

**Comment by graphicore** [comment]
Thanks for reporting. Technically it"s not broken, because it was never active. Maybe this is a good start:: https://stackoverflow.com/questions/47337817/how-to-setup-letsencrypt-for-google-cloud-compute-engine-load-balancer

**Comment by graphicore** [comment]
More resources:

https://cloud.google.com/load-balancing/docs/ssl-certificates

https://medium.com/google-cloud/kubernetes-w-lets-encrypt-cloud-dns-c888b2ff8c0e

**Comment by graphicore** [comment]
Now at https://fontbakery.graphicore.de but it's in a nonstable state and has only one worker pod available at the moment.
