### ISSUE TITLE
Feature: catalog status discovery/query for specific checks 

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery-dashboard#86]
> The dashboard is going to need to have a UI for querying a given check or set of checks against the catalog to see an overview of the status of the collection in terms of the particular issue. 

> […] the next focus is this kind of catalog status discovery, and perhaps a commenting/approval/prioritization layer to annotate the rethinkdb info.....

We'l have to plan this in more detail.

**Comment by graphicore** [comment]
> - A query mechanism so you can see the flow of any particular checkID, or set of checks, across the catalog (e.g. font name & post table version numbers; or the fsType checkID)

**Comment by davelab6** [comment]
https://github.com/googlefonts/fontbakery/issues/2213 is a candidate check for this
